spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library
    username: localuser
    password: localpass

logging:
  level:
    org.springframework.r2dbc: DEBUG

jwt:
  secret: asqwecfqwfqwfqwfqwfqwfqwfqwfqwfqwfqwf123123123123123123123
  expiration: 3218000