spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library
    username: localuser
    password: localpass

logging:
  level:
    org.springframework.r2dbc: DEBUG

custom:
  flyway:
    url: jdbc:postgresql://localhost:5432/library
    user: localuser
    password: localpass
    path: classpath:db/migration
    baseline-on-migrate: true
  jwt:
    secret: asqwecfqwfqwfqwfqwfqwfqwfqwfqwfqwfqwf123123123123123123123
    expiration: 3218000