spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/library
    username: localuser
    password: localpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: asqwecfqwfqwfqwfqwfqwfqwfqwfqwfqwfqwf123123123123123123123
  expiration: 3218000